language: c++

sudo: required

compiler:
  - gcc
  - clang
os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

  #Codecov
  - sudo pip install codecov
  - chmod +x .get_code_cov.sh

  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

install:
 
  #Codecov
  - sudo apt-get install g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

script:
  #Compile without optimization and with coverage
  - make test
  #Run the program for different tests.
  - cd bin/
  - ./Dirac_vs_Majorana
  - cd ..
  #Codecov
  - ./.get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
